name: vagrant-up

on: [push]

jobs:
  setup:
    strategy:
      fail-fast: false
      matrix:
        distributions: [melodic-bionic , noetic-focal]
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Install vagrant
      run: brew install vagrant
    - name: Install vagrant cacher
      run:  vagrant plugin install vagrant-cachier
    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-
    - name: Run vagrant up
      run: vagrant up
      working-directory: ./${{matrix.distributions}}
    - name: ssh into box after boot
      run: vagrant ssh -c "echo 'hello world!'"
      working-directory: ./${{matrix.distributions}}
    # - name: vagrant halt
    #   run: vagrant halt
    #   working-directory: ./${{matrix.distributions}}
    - name: vagrant login
      run: vagrant cloud auth login --token ${{secrets.VAGRANT_ACCESS_TOKEN}}
    - name: package
      run: vagrant package
      working-directory: ./${{matrix.distributions}}
    - name: vagrant box create --short-description "Vagrant ROS Image" 
      run: vagrant box create togawa83/${{matrix.distributions}} || echo already exists
    - name: vagrant upload
      run: vagrant cloud provider upload togawa83/${{matrix.distributions}} virtualbox $GITHUB_RUN_ID package.box
      working-directory: ./${{matrix.distributions}}
